/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: mgifbx (https://sketchfab.com/mgifbx)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/jerry-the-tom-and-jerry-show-6964d63403a444beb672e79a0118c493
Title: Jerry - The Tom and Jerry Show
*/

import React, { useRef } from "react";
import jerry from '../assets/3d/jerry_-_the_tom_and_jerry_show.glb';
import { useGLTF } from "@react-three/drei";

const Jerry = () => {
  const { nodes, materials } = useGLTF(jerry);
  return (
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.jerry}
        rotation={[-Math.PI / 2, 0, 0]}
      />
  );
}

export default Jerry